services:
  backend:
    image: ${ECR_BACKEND_IMAGE}
    env_file:
      - .env
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./static/uploads:/app/static/uploads

  frontend:
    image: ${ECR_FRONTEND_IMAGE}
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend